name: Build and Attach Earthman PRG to Release

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to upload assets to releases
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dasm
        run: |
          sudo apt-get update
          sudo apt-get install -y dasm

      - name: Build with dasm
        run: dasm main.asm -oearthman.prg

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}  # Use the release's upload URL
          asset_path: ./earthman.prg
          asset_name: earthman.prg
          asset_content_type: application/octet-stream
